import { loadGeneratedGeometry } from '../../core/product/generated';
import type { ProductDefinition } from '../../core/product/types';
import { canopyTent } from '../canopy-tent/definition';
import generatedJson from './generated/surfaces.json';

const generated = loadGeneratedGeometry(generatedJson);

/**
 * A second product on the same engine: a step-and-repeat backdrop banner. Its model is
 * generated by `scripts/build-banner.ts`. Nothing in the engine is banner-specific; the
 * differences (one or two faces, a different frame, different options) are all data.
 */
export const backdropBanner: ProductDefinition = {
  id: 'backdrop-banner',
  name: 'Step & Repeat Backdrop',
  tagline: 'Dye-sublimation fabric backdrop on a telescopic stand',
  atlasSize: generated.atlasSize,
  geometryOption: 'size',
  geometry: generated.variants,
  surfaceGroups: [{ id: 'face', label: 'Faces' }],
  surfaceLabels: { 'face-front': 'Front face', 'face-back': 'Back face' },
  options: [
    {
      id: 'size',
      label: 'Size',
      defaultChoice: '8x8',
      choices: [
        { id: '8x8', label: "8' × 8'" },
        { id: '10x8', label: "10' × 8'" },
      ],
    },
    {
      id: 'sides',
      label: 'Print',
      defaultChoice: 'single',
      choices: [
        { id: 'single', label: 'Single-sided' },
        { id: 'double', label: 'Double-sided' },
      ],
    },
    {
      id: 'production',
      label: 'Production',
      defaultChoice: 'standard',
      choices: [
        { id: 'standard', label: 'Standard', description: 'Ships in 5 business days' },
        { id: 'rush', label: 'Rush', description: 'Ships in 2 business days' },
      ],
    },
  ],
  surfaceAvailability: [{ surface: 'face-back', option: 'sides', availableFor: ['double'] }],
  unprintedFill: '#f2f2f2',
  palette: canopyTent.palette,
  defaultFill: '#ffffff',
  fonts: canopyTent.fonts,
  views: [
    { id: 'orbit', label: 'Orbit', direction: [1.2, 0.35, 2.1] },
    { id: 'front', label: 'Front', direction: [0, 0.1, 2.4] },
    { id: 'back', label: 'Back', direction: [0, 0.1, -2.4] },
  ],
  scene: {
    materialColor: [{ role: 'frame', option: 'size', colors: { '8x8': '#1d1e22', '10x8': '#1d1e22' }, metalness: 0.7, roughness: 0.4 }],
  },
  limits: canopyTent.limits,
};
